Bump ammonite to 0.6.2
Had a look a bit at how things have changed, but not all the way, so this was
enough for me to run:

    repl/run -language:_ -Yno-predef -Yno-adapted-args -Yno-imports -Xlog-implicits

.. and not run into:

    scala.MatchError: INFO (of class scala.tools.nsc.reporters.Reporter$INFO$)
      ammonite.repl.interp.Compiler$$anon$2.display(Compiler.scala:120)

The fix is actually in 0.5.8, but I went for latest.

https://github.com/lihaoyi/Ammonite/commit/63d102733cbf759fa7cc6e8b7c3e993533307505#diff-a08d4cf136a9d0be5e970c1bbc567d00R127