Throw scala.StringContext out
For string interpolation Scala requires there to be a StringContext term in
scope, but that doesn't have to be scala.StringContext:

    // Documenting that it is intentional that the ident is not rooted for purposes of virtualization
    //val t1 = atPos(o2p(start)) { Select(Select (Ident(nme.ROOTPKG), nme.scala_), nme.StringContext) }
      val t1 = atPos(o2p(start)) { Ident(nme.StringContext) }

From https://github.com/scala/scala/blob/v2.11.8/src/compiler/scala/tools/nsc/ast/parser/Parsers.scala#L1304-L1306

Therefore the StringContext in the standard library, which provides a number of
intepolators - all that take Anys, can be thrown out and replaced with a better,
more principled one.

Before:

    psp> val xs = 1 to 20
    xs: IntRange = [1..20]

    psp> pp"$xs"
    res3: String = [1..20]

    psp> s"$xs"
    res4: String = psp.std.Consecutive$Closed@77228160

After:

    psp> val xs = 1 to 20
    xs: IntRange = [1..20]

    psp> pp"$xs"
    res3: String = [1..20]

    psp> s"$xs"
    Main.scala:1033: value s is not a member of psp.std.StringContext
    s"$xs"
    ^

    Compilation Failed

Also, replace all the s-interpolator usages for psp-std interpolators, except
for in macros, where attempts to re-wire Quasiquote to use psp.std.StringContext
failed..